channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=24.0
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.1.2
  - numpy==1.26.2
  - packaging==23.2
  - pandas==2.1.4
  - pyyaml==6.0.3
  - scikit-learn==1.3.2
  - scipy==1.16.3
  - xgboost==2.0.3
name: mlflow-env
